/* =============================================================
   BAKU — manifest de marca
   Datos de producto para carrito, wishlist, búsqueda, quick view
   y página de producto. El contenido crítico vive hardcodeado
   en el HTML; este archivo enriquece la capa interactiva.
   ============================================================= */
(function () {
  "use strict";

  window.__BRAND__ = {
    name: "BAKU",
    tagline: "Indumentaria masculina — Nueva Córdoba, CBA.",
    currency: "ARS",

    products: [
      {
        id: "tee-piedra-negro",
        name: "Remera Oversize Piedra",
        color: "Tinta",
        price: 58000,
        oldPrice: null,
        badge: "nuevo",
        category: "remeras",
        sizes: ["S", "M", "L", "XL", "XXL"],
        desc: "Jersey peinado 240 g/m². Hombro caído, cuello reforzado con tapacostura. Teñida en prenda para un tono profundo e irregular.",
        material: "100% algodón peinado 240 g/m², teñido en prenda.",
        fit: "Oversize real: hombro caído y largo extra. Si la querés al cuerpo, bajá un talle.",
        care: "Lavar del revés con agua fría. No usar secadora. Plancha media sin tocar el sello.",
        art: "g-tee",
        views: ["g-tee", "g-tee-b"],
        variants: ["tee-piedra-negro", "tee-piedra-hueso"],
        colorway: { g1: "#211E18", g2: "#171511", g3: "#3A362D" }
      },
      {
        id: "tee-piedra-hueso",
        name: "Remera Oversize Piedra",
        color: "Hueso",
        price: 58000,
        oldPrice: null,
        badge: null,
        category: "remeras",
        sizes: ["S", "M", "L", "XL", "XXL"],
        desc: "Jersey peinado 240 g/m². Hombro caído, cuello reforzado con tapacostura. Sin blanqueo óptico: el color del algodón, tal cual.",
        material: "100% algodón peinado 240 g/m², sin blanqueo óptico.",
        fit: "Oversize real: hombro caído y largo extra. Si la querés al cuerpo, bajá un talle.",
        care: "Lavar del revés con agua fría. No usar secadora. Plancha media sin tocar el sello.",
        art: "g-tee",
        views: ["g-tee", "g-tee-b"],
        variants: ["tee-piedra-negro", "tee-piedra-hueso"],
        colorway: { g1: "#E4DDCF", g2: "#CFC6B4", g3: "#BFB5A0" }
      },
      {
        id: "hoodie-bruma-niebla",
        name: "Hoodie Bruma",
        color: "Niebla",
        price: 112000,
        oldPrice: null,
        badge: "nuevo",
        category: "buzos",
        sizes: ["S", "M", "L", "XL"],
        desc: "Frisa invisible 460 g/m², capucha de doble capa sin cordón a la vista. Puños y cintura en rib pesado.",
        material: "Frisa de algodón 460 g/m² con interior perchado. Rib 2×2 en puños y cintura.",
        fit: "Calce relajado con capucha estructurada de doble capa.",
        care: "Lavar con agua fría, del revés. Secado a la sombra. No retorcer.",
        art: "g-hoodie",
        views: ["g-hoodie", "g-hoodie-b"],
        variants: ["hoodie-bruma-niebla", "hoodie-bruma-tinta"],
        colorway: { g1: "#B6B1A6", g2: "#9C968A", g3: "#8A8478" }
      },
      {
        id: "hoodie-bruma-tinta",
        name: "Hoodie Bruma",
        color: "Tinta",
        price: 89600,
        oldPrice: 112000,
        badge: "-20%",
        category: "buzos",
        sizes: ["S", "M", "L", "XL"],
        desc: "Frisa invisible 460 g/m², capucha de doble capa sin cordón a la vista. Puños y cintura en rib pesado.",
        material: "Frisa de algodón 460 g/m² con interior perchado. Rib 2×2 en puños y cintura.",
        fit: "Calce relajado con capucha estructurada de doble capa.",
        care: "Lavar con agua fría, del revés. Secado a la sombra. No retorcer.",
        art: "g-hoodie",
        views: ["g-hoodie", "g-hoodie-b"],
        variants: ["hoodie-bruma-niebla", "hoodie-bruma-tinta"],
        colorway: { g1: "#25221B", g2: "#1A1813", g3: "#3C382E" }
      },
      {
        id: "crewneck-sur",
        name: "Crewneck Sur",
        color: "Arena",
        price: 98000,
        oldPrice: null,
        badge: null,
        category: "buzos",
        sizes: ["S", "M", "L", "XL"],
        desc: "Cuello redondo con rib en V, manga montada. Frisa de algodón orgánico con interior perchado.",
        material: "Frisa de algodón orgánico certificado, interior perchado suave.",
        fit: "Calce clásico con hombro montado. Fiel al talle.",
        care: "Lavar con agua fría. Secar en plano para conservar la forma.",
        art: "g-crew",
        views: ["g-crew", "g-crew-b"],
        variants: ["crewneck-sur"],
        colorway: { g1: "#CBBBA0", g2: "#B5A488", g3: "#A69476" }
      },
      {
        id: "camisa-taller",
        name: "Camisa Taller",
        color: "Crudo",
        price: 89000,
        oldPrice: null,
        badge: "nuevo",
        category: "camisas",
        sizes: ["S", "M", "L", "XL"],
        desc: "Sarga de trabajo 320 g/m², bolsillos plato al tono, botones de pasta. Corte recto de taller.",
        material: "Sarga de algodón 320 g/m² sin teñir. Botones de pasta italiana.",
        fit: "Corte recto de taller. Entra cómoda sobre una remera pesada.",
        care: "Lavar con agua fría. Se arruga con dignidad: plancha opcional.",
        art: "g-shirt",
        views: ["g-shirt", "g-shirt-b"],
        variants: ["camisa-taller"],
        colorway: { g1: "#DDD5C3", g2: "#C8BEA8", g3: "#B3A88F" }
      },
      {
        id: "campera-ruta",
        name: "Campera Denim Ruta",
        color: "Índigo lavado",
        price: 164000,
        oldPrice: null,
        badge: null,
        category: "abrigos",
        sizes: ["S", "M", "L", "XL"],
        desc: "Denim 14 oz con lavado a la piedra. Costuras en contraste tono arena, herrajes de zamac envejecido.",
        material: "Denim rígido 14 oz, lavado a la piedra. Herrajes de zamac envejecido.",
        fit: "Caja recta noventosa. El denim cede ~medio talle con el uso.",
        care: "Lavar lo menos posible, con agua fría y del revés. El desgaste es parte del diseño.",
        art: "g-jacket",
        views: ["g-jacket", "g-jacket-b"],
        variants: ["campera-ruta"],
        colorway: { g1: "#46536B", g2: "#39445A", g3: "#2E374A" }
      },
      {
        id: "cargo-franco",
        name: "Pantalón Cargo Franco",
        color: "Oliva",
        price: 124000,
        oldPrice: null,
        badge: "últimas",
        category: "pantalones",
        sizes: ["38", "40", "42", "44", "46"],
        desc: "Gabardina rígida 300 g/m², bolsillos fuelle laterales, cintura con cordón interno. Calce relajado, botamanga recta.",
        material: "Gabardina de algodón 300 g/m². Cordón interno de cintura.",
        fit: "Calce relajado con botamanga recta. Tiro medio-alto.",
        care: "Lavar con agua fría. Secado colgado para mantener la caída.",
        art: "g-pants",
        views: ["g-pants", "g-pants-b"],
        variants: ["cargo-franco"],
        colorway: { g1: "#6E6C53", g2: "#5D5B45", g3: "#4E4C3A" }
      },
      {
        id: "gorra-sello",
        name: "Gorra Sello",
        color: "Tinta",
        price: 38000,
        oldPrice: null,
        badge: null,
        category: "accesorios",
        sizes: ["Único"],
        desc: "Corona de 6 paneles en gabardina lavada, sello bordado al frente, hebilla metálica trasera.",
        material: "Gabardina de algodón lavada. Bordado al tono, hebilla de metal.",
        fit: "Talle único regulable con hebilla trasera.",
        care: "Limpiar con paño húmedo. No lavar a máquina.",
        art: "g-cap",
        views: ["g-cap"],
        variants: ["gorra-sello"],
        colorway: { g1: "#24211B", g2: "#191713", g3: "#39352B" }
      },
      {
        id: "beanie-puerto",
        name: "Beanie Puerto",
        color: "Arena",
        price: 32000,
        oldPrice: null,
        badge: "nuevo",
        category: "accesorios",
        sizes: ["Único"],
        desc: "Tejido rib 2×2 en lana merino. Doblez ancho con etiqueta tejida al tono.",
        material: "Lana merino extrafina, tejido rib 2×2.",
        fit: "Talle único con doblez regulable.",
        care: "Lavar a mano con jabón neutro. Secar en plano.",
        art: "g-beanie",
        views: ["g-beanie"],
        variants: ["beanie-puerto"],
        colorway: { g1: "#C9B99E", g2: "#B2A084", g3: "#A08E71" }
      },
      {
        id: "tote-diario",
        name: "Tote Diario",
        color: "Crudo",
        price: 28000,
        oldPrice: null,
        badge: null,
        category: "accesorios",
        sizes: ["Único"],
        desc: "Lona de algodón 12 oz sin teñir, manijas reforzadas con costura en X. Sello serigrafiado a un color.",
        material: "Lona de algodón 12 oz sin teñir. Serigrafía a un color.",
        fit: "40 × 38 cm, manijas de 60 cm. Entra una notebook de 14”.",
        care: "Lavar a mano con agua fría. La lona se ablanda con el uso.",
        art: "g-tote",
        views: ["g-tote"],
        variants: ["tote-diario"],
        colorway: { g1: "#E0D8C6", g2: "#CBC1AA", g3: "#B7AC92" }
      },
      {
        id: "medias-par-03",
        name: "Medias Par 03",
        color: "Mixto ×3",
        price: 18000,
        oldPrice: 24000,
        badge: "-25%",
        category: "accesorios",
        sizes: ["35-39", "40-45"],
        desc: "Pack de tres pares en algodón peinado: tinta, hueso y arena. Puño con rib alto y talón reforzado.",
        material: "Algodón peinado con talón y puntera reforzados.",
        fit: "Puño rib alto que no cede. Pack de 3 pares.",
        care: "Lavar con agua fría. No usar secadora.",
        art: "g-socks",
        views: ["g-socks"],
        variants: ["medias-par-03"],
        colorway: { g1: "#E2DBCB", g2: "#26231C", g3: "#C0B096" }
      }
    ],

    shipping: "Envíos a todo el país · Gratis desde $150.000",
    contact: {
      email: "bakunuevacordoba@gmail.com",
      phone: "+54 9 3541 23-1729",
      whatsapp: "https://wa.me/5493541231729",
      address: "Montevideo 32, Nueva Córdoba — Córdoba, Argentina",
      ig: "@baku.cba",
      facebook: "https://www.facebook.com/Bakunuevacordoba/"
    }
  };
})();
